<?php

namespace CoreBundle\Repository;

/**
 * WeatherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeatherRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearchStatistics() : array
    {
        $mostSearchedCity = $this->createQueryBuilder("s")
            ->select("s.city, COUNT(s.id) as total")
            ->orderBy("total", "DESC")
            ->groupBy("s.city")
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        $totalSearches = $this->createQueryBuilder("s")
            ->select("COUNT(s.id) AS searchCount")
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        $avgTemps = $this->createQueryBuilder("s")
            ->select("
                AVG(s.temperatureNow) as temperatureAvg,
                MIN(s.temperatureNow) as temperatureMin,
                MAX(s.temperatureNow) as temperatureMax
            ")
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        return [
            'temperatures' => $avgTemps,
            'mostSearchedCity' => $mostSearchedCity['city'],
            'totalSearchesCount' => $totalSearches['searchCount'],
        ];
    }
}
